// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RpcTypeProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("RpcTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing RpcTypeProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RpcTypeProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "RpcTypeProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing RpcTypeProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
